apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-advanced
  annotations:
    # This annotation ensures Projects (Namespaces) are created first when deployed via Argo CD
    argocd.argoproj.io/sync-wave: "-1"
spec:
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: false
  - stage: staging
    autoPromotionEnabled: true
  - stage: ab-test-a
    autoPromotionEnabled: true
  - stage: ab-test-b
    autoPromotionEnabled: true
  - stage: prod-central
    autoPromotionEnabled: true
  - stage: prod-east
    autoPromotionEnabled: false
  - stage: prod-west
    autoPromotionEnabled: false
